<?php


namespace WANGHORN\Entity\Password;


use Sm\Core\Util;
use Sm\Data\Type\Exception\CannotCastException;
use Sm\Data\Type\String_;

class PasswordDatatype extends String_ {
    public function jsonSerialize() {
        return '*********';
    }
    public function setSubject($subject) {
        if (!is_string($subject) && isset($subject)) {
            throw new CannotCastException("Cannot set password to anything but a string " . Util::getShape($subject));
        }
        return parent::setSubject($subject); // TODO: Change the autogenerated stub
    }
    
    public function resolve() {
        return $this->subject;
    }
}