export const FETCH_MODELS_RECEIVED      = "FETCH_MODELS_RECEIVED";
export const FETCH_MODELS               = "FETCH_MODELS_BEGIN";
export const FETCH_MODEL_METAS_RECEIVED = "FETCH_MODEL_METAS_RECEIVED";
export const FETCH_MODEL_METAS          = "FETCH_MODEL_METAS";
export const EXECUTE_MODEL_QUERY__END = 'EXECUTE_MODEL_QUERY__END';