export const FETCH_SM_ENTITY_SCHEMATIC          = 'FETCH_SM_ENTITY_SCHEMATIC';
export const FETCH_SM_ENTITY_SCHEMATIC_RECEIVED = 'FETCH_SM_ENTITY_SCHEMATIC_RECEIVED';
export const FETCH_SM_ENTITIES                  = 'FETCH_SM_ENTITIES';
export const FETCH_SM_ENTITIES_RECEIVED         = 'FETCH_SM_ENTITIES_RECEIVED';


