export const FETCH_SM_ENTITY_SCHEMATIC          = 'FETCH_SM_ENTITY_SCHEMATIC';
export const FETCH_SM_ENTITY_SCHEMATIC_RECEIVED = 'FETCH_SM_ENTITY_SCHEMATIC_RECEIVED';
export const FETCH_SM_ENTITIES                  = 'FETCH_SM_ENTITIES';
export const FETCH_SM_ENTITIES_RECEIVED         = 'FETCH_SM_ENTITIES_RECEIVED';


export const PERSIST_SM_ENTITY           = "PERSIST_SM_ENTITY";
export const PERSIST_SM_ENTITY_COMPLETED = "PERSIST_SM_ENTITY_COMPLETED";
export const PERSIST_SM_ENTITY_FAILED    = "PERSIST_SM_ENTITY_FAILED";