export const FETCH_ENTITY_METAS_RECEIVED     = "FETCH_ENTITY_METAS_RECEIVED";
export const FETCH_ENTITY_METAS              = "FETCH_ENTITY_METAS_BEGIN";
export const FETCH_ENTITY_INSTANCES          = "FETCH_ENTITIES_BEGIN";
export const FETCH_ENTITY_INSTANCES_RECEIVED = "FETCH_ENTITY_INSTANCES_RECEIVED";
export const ENTITY_INSTANCE_RESOLVED        = "ENTITY_INSTANCE_RESOLVED";