export const FETCH_ENTITY_METAS_RECEIVED = "FETCH_ENTITY_METAS_RECEIVED";
export const FETCH_ENTITY_METAS          = "FETCH_ENTITY_METAS_BEGIN";

export const FETCH_ENTITIES              = "FETCH_ENTITIES_BEGIN";
export const FETCH_ENTITIES_RECEIVED     = "FETCH_ENTITIES_RECEIVED";
